### ISSUE TITLE
stuck after selecting object mesh

### ISSUE THREAD

**Issue by jessiezixinWang** [ammar-n-abbas/FoundationPoseROS2#1]
Hi, thank you for your nice work. I use the docker image provided by FoundationPose. 

At first, when I run foundationpose_ros_multi.py, I got error message:
```
Traceback (most recent call last):
  File "foundationpose_ros_multi.py", line 377, in <module>
    main()
  File "foundationpose_ros_multi.py", line 371, in main
    node = PoseEstimationNode(new_file_paths)
  File "foundationpose_ros_multi.py", line 130, in __init__
    self.seg_model = SAM("sam2_b.pt")
  File "/opt/conda/envs/my/lib/python3.8/site-packages/ultralytics/vit/sam/model.py", line 19, in __init__
    self.model = build_sam(model)
  File "/opt/conda/envs/my/lib/python3.8/site-packages/ultralytics/vit/sam/build.py", line 125, in build_sam
    raise FileNotFoundError(f'{ckpt} is not a supported sam model. Available models are: \n {sam_model_map.keys()}')
FileNotFoundError: sam2_b.pt is not a supported sam model. Available models are: 
 dict_keys(['sam_h.pt', 'sam_l.pt', 'sam_b.pt'])
```

Then I change the script from     self.seg_model = SAM("sam2_b.pt") to self.seg_model = SAM("sam_b.pt")
After selecting the object mesh, it stuck with the sentence "[__init__()] init done". May I ask how to solve this problem?

```
(my) root@jessie-HP-Z4-G4-Workstation:/home/jessie/FoundationPoseROS2# python foundationpose_ros_multi.py
Warp 1.0.2 initialized:
   CUDA Toolkit 11.5, Driver 12.2
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA GeForce RTX 4090" (24 GiB, sm_89, mempool enabled)
   Kernel cache:
     /root/.cache/warp/1.0.2
[__init__()] self.cfg: 
 lr: 0.0001
c_in: 6
zfar: 'Infinity'
debug: null
n_view: 1
run_id: 3wy8qqex
use_BN: true
exp_name: 2024-01-11-20-02-45
n_epochs: 62
save_dir: /home/bowenw/debug/2024-01-11-20-02-45/
use_mask: false
loss_type: pairwise_valid
optimizer: adam
batch_size: 64
crop_ratio: 1.1
enable_amp: true
use_normal: false
max_num_key: null
warmup_step: -1
input_resize:
- 160
- 160
max_step_val: 1000
vis_interval: 1000
weight_decay: 0
normalize_xyz: true
resume_run_id: null
clip_grad_norm: 'Infinity'
lr_epoch_decay: 500
render_backend: nvdiffrast
train_num_pair: 5
lr_decay_epochs:
- 50
n_epochs_warmup: 1
make_pair_online: false
gradient_max_norm: 'Infinity'
max_step_per_epoch: 10000
n_rendering_workers: 1
save_epoch_interval: 100
n_dataloader_workers: 100
split_objects_across_gpus: true
ckpt_dir: /home/jessie/FoundationPoseROS2/FoundationPose/learning/training/../../weights/2024-01-11-20-02-45/model_best.pth

[__init__()] self.h5_file:None
[__init__()] Using pretrained model from /home/jessie/FoundationPoseROS2/FoundationPose/learning/training/../../weights/2024-01-11-20-02-45/model_best.pth
[__init__()] init done
[__init__()] welcome
[__init__()] self.cfg: 
 lr: 0.0001
c_in: 6
zfar: .inf
debug: null
w_rot: 0.1
n_view: 1
run_id: null
use_BN: true
rot_rep: axis_angle
ckpt_dir: /home/jessie/FoundationPoseROS2/FoundationPose/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth
exp_name: 2023-10-28-18-33-37
save_dir: /tmp/2023-10-28-18-33-37/
loss_type: l2
optimizer: adam
trans_rep: tracknet
batch_size: 64
crop_ratio: 1.2
use_normal: false
BN_momentum: 0.1
max_num_key: null
warmup_step: -1
input_resize:
- 160
- 160
max_step_val: 1000
normal_uint8: false
vis_interval: 1000
weight_decay: 0
n_max_objects: null
normalize_xyz: true
clip_grad_norm: 'Infinity'
rot_normalizer: 0.3490658503988659
trans_normalizer:
- 0.019999999552965164
- 0.019999999552965164
- 0.05000000074505806
max_step_per_epoch: 25000
val_epoch_interval: 10
n_dataloader_workers: 60
enable_amp: true
use_mask: false

[__init__()] self.h5_file:
[__init__()] Using pretrained model from /home/jessie/FoundationPoseROS2/FoundationPose/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth
[__init__()] init done
```

**Comment by ammar-n-abbas** [comment]
@jessiezixinWang Thank you.

Can you share the snapshot of the mesh selection window? 
Normally, when you click on the object it should display on the terminal a message of 
"Object 0 selected..."

Once you select the required object you can press enter to start tracking.

**Comment by ammar-n-abbas** [comment]
@jessiezixinWang can you share the snapshot after this GUI when you press done and select a object

**Comment by jessiezixinWang** [comment]
<img width="1025" alt="image" src="https://github.com/user-attachments/assets/b522abf0-b200-41f6-87af-6cdc8c3eba1f">
This is the snapshot after I press done

**Comment by ammar-n-abbas** [comment]
Can you check the camera topic and change that accordingly in the code.

Sometimes it is /camera/camera/...

**Comment by ammar-n-abbas** [comment]
It seems more like a dependency issue

**Comment by Goddard-Wen** [comment]
I also Stuck in here. Is it necessary to have a camera to run this project?

![Image](https://github.com/user-attachments/assets/3fa5481a-3cd4-4013-95ce-ed214be518e4)

**Comment by ammar-n-abbas** [comment]
@Goddard-Wen yes unless you run the rosbag with the camera topics. Make sure to match the camera topic with the subscriber in the code.

**Comment by YOODS-Xu** [comment]
I also stuck in here. After I run "python foundationpose_ros_multi.py", three /camera/camera topics were added as below.And it was stopped at the line [__init__()] init done.
May I ask how to solve this problem 

/camera/camera/aligned_depth_to_color/image_raw
/camera/camera/color/camera_info
/camera/camera/color/image_raw

**Comment by YOODS-Xu** [comment]
@ammar-n-abbas @jessiezixinWang @Goddard-Wen 
Any advice is greatly appreciated.
