### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by JINAOLONG** [ammar-n-abbas/FoundationPoseROS2#7]
Hi, I select an object and then select input, but it results in a runtime error.
**Terminal Information**
(foundationpose_ros2) a@robot:/data/project/FoundationPoseROS2$ python ./foundationpose_ros_multi.py
Warp 1.3.1 initialized:
   CUDA Toolkit 12.5, Driver 12.4
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA RTX A6000" (47 GiB, sm_86, mempool enabled)
     "cuda:1"   : "NVIDIA RTX A6000" (47 GiB, sm_86, mempool enabled)
   CUDA peer access:
     Supported fully (all-directional)
   Kernel cache:
     /home/a/.cache/warp/1.3.1
[__init__()] self.cfg: 
 lr: 0.0001
c_in: 6
zfar: 'Infinity'
debug: null
n_view: 1
run_id: 3wy8qqex
use_BN: true
exp_name: 2024-01-11-20-02-45
n_epochs: 62
save_dir: /home/bowenw/debug/2024-01-11-20-02-45/
use_mask: false
loss_type: pairwise_valid
optimizer: adam
batch_size: 64
crop_ratio: 1.1
enable_amp: true
use_normal: false
max_num_key: null
warmup_step: -1
input_resize:
- 160
- 160
max_step_val: 1000
vis_interval: 1000
weight_decay: 0
normalize_xyz: true
resume_run_id: null
clip_grad_norm: 'Infinity'
lr_epoch_decay: 500
render_backend: nvdiffrast
train_num_pair: 5
lr_decay_epochs:
- 50
n_epochs_warmup: 1
make_pair_online: false
gradient_max_norm: 'Infinity'
max_step_per_epoch: 10000
n_rendering_workers: 1
save_epoch_interval: 100
n_dataloader_workers: 100
split_objects_across_gpus: true
ckpt_dir: /data/project/FoundationPoseROS2/FoundationPose/learning/training/../../weights/2024-01-11-20-02-45/model_best.pth

[__init__()] self.h5_file:None
[__init__()] Using pretrained model from /data/project/FoundationPoseROS2/FoundationPose/learning/training/../../weights/2024-01-11-20-02-45/model_best.pth
[__init__()] init done
[__init__()] welcome
[__init__()] self.cfg: 
 lr: 0.0001
c_in: 6
zfar: .inf
debug: null
w_rot: 0.1
n_view: 1
run_id: null
use_BN: true
rot_rep: axis_angle
ckpt_dir: /data/project/FoundationPoseROS2/FoundationPose/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth
exp_name: 2023-10-28-18-33-37
save_dir: /tmp/2023-10-28-18-33-37/
loss_type: l2
optimizer: adam
trans_rep: tracknet
batch_size: 64
crop_ratio: 1.2
use_normal: false
BN_momentum: 0.1
max_num_key: null
warmup_step: -1
input_resize:
- 160
- 160
max_step_val: 1000
normal_uint8: false
vis_interval: 1000
weight_decay: 0
n_max_objects: null
normalize_xyz: true
clip_grad_norm: 'Infinity'
rot_normalizer: 0.3490658503988659
trans_normalizer:
- 0.019999999552965164
- 0.019999999552965164
- 0.05000000074505806
max_step_per_epoch: 25000
val_epoch_interval: 10
n_dataloader_workers: 60
enable_amp: true
use_mask: false

[__init__()] self.h5_file:
[__init__()] Using pretrained model from /data/project/FoundationPoseROS2/FoundationPose/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth
[__init__()] init done
[INFO] [1732369121.290993259] [pose_estimation_node]: Camera intrinsic matrix initialized: [[     895.45           0      649.12]
 [          0       896.3       359.8]
 [          0           0           1]]

0: 1024x1024 1 0, 1 1, 1 2, 1 3, 1 4, 1 5, 1 6, 1 7, 1 8, 1 9, 1 10, 1 11, 2762.4ms
Speed: 21.3ms preprocess, 2762.4ms inference, 0.7ms postprocess per image at shape (1, 3, 1024, 1024)
[INFO] [1732369129.194321491] [pose_estimation_node]: Object 0 selected.
Traceback (most recent call last):
  File "/data/project/FoundationPoseROS2/./foundationpose_ros_multi.py", line 236, in click_event
    model_pts=temp_mesh.vertices,
AttributeError: 'Scene' object has no attribute 'vertices'
[INFO] [1732369136.964438968] [pose_estimation_node]: Object 1 selected.
[reset_object()] self.diameter:0.2973231969400526, vox_size:0.01486615984700263
[reset_object()] self.pts:torch.Size([528, 3])
[reset_object()] reset done
[make_rotation_grid()] cam_in_obs:(42, 4, 4)
[make_rotation_grid()] rot_grid:(252, 4, 4)
num original candidates = 252
num of pose after clustering: 252
[make_rotation_grid()] after cluster, rot_grid:(252, 4, 4)
[make_rotation_grid()] self.rot_grid: torch.Size([252, 4, 4])
[register()] Welcome
Module Utils 64702ec load on device 'cuda:0' took 0.40 ms  (cached)
[register()] valid too small, return
[guess_translation()] valid is empty
[track_one()] Please init pose by register first
Traceback (most recent call last):
  File "/data/project/FoundationPoseROS2/./foundationpose_ros_multi.py", line 394, in <module>
    main()
  File "/data/project/FoundationPoseROS2/./foundationpose_ros_multi.py", line 389, in main
    rclpy.spin(node)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 222, in spin
    executor.spin_once()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 739, in spin_once
    self._spin_once_impl(timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 736, in _spin_once_impl
    raise handler.exception()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 239, in __call__
    self._handler.send(None)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 437, in handler
    await call_coroutine(entity, arg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 362, in _execute_subscription
    await await_or_execute(sub.callback, msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 107, in await_or_execute
    return callback(*args)
  File "/data/project/FoundationPoseROS2/./foundationpose_ros_multi.py", line 165, in depth_callback
    self.process_images()
  File "/data/project/FoundationPoseROS2/./foundationpose_ros_multi.py", line 326, in process_images
    pose = pose_est.track_one(rgb=color, depth=depth, K=self.cam_K, iteration=args.track_refine_iter)
  File "/data/project/FoundationPoseROS2/./FoundationPose/estimater.py", line 253, in track_one
    raise RuntimeError
RuntimeError

**Comment by ammar-n-abbas** [comment]
Have you tried it on the demo rosbag?

**Comment by ammar-n-abbas** [comment]
Please check your camera topics

**Comment by JINAOLONG** [comment]
> Please check your camera topics

Thank you very much, I checked the camera topic and the initialization issue that was resolved and still had the initial problem.

Traceback (most recent call last):
  File "/data/project/FoundationPoseROS2/./foundationpose_ros_multi.py", line 395, in <module>
    main()
  File "/data/project/FoundationPoseROS2/./foundationpose_ros_multi.py", line 390, in main
    rclpy.spin(node)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 222, in spin
    executor.spin_once()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 739, in spin_once
    self._spin_once_impl(timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 736, in _spin_once_impl
    raise handler.exception()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 239, in __call__
    self._handler.send(None)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 437, in handler
    await call_coroutine(entity, arg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 362, in _execute_subscription
    await await_or_execute(sub.callback, msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 107, in await_or_execute
    return callback(*args)
  File "/data/project/FoundationPoseROS2/./foundationpose_ros_multi.py", line 165, in depth_callback
    self.process_images()
  File "/data/project/FoundationPoseROS2/./foundationpose_ros_multi.py", line 327, in process_images
    pose = pose_est.track_one(rgb=color, depth=depth, K=self.cam_K, iteration=args.track_refine_iter)
  File "/data/project/FoundationPoseROS2/./FoundationPose/estimater.py", line 253, in track_one
    raise RuntimeError
RuntimeError
段错误 (核心已转储)

**Comment by ammar-n-abbas** [comment]
can you share full terminal log or screen recording? Which camera are you using?

**Comment by JINAOLONG** [comment]
> can you share full terminal log or screen recording? Which camera are you using?

Here's the full terminal log, the camera I'm using is a realsenseL515

(foundationpose_ros2) a@robot:/data/project/FoundationPoseROS2$ python ./foundationpose_ros_multi.py 
Warp 1.3.1 initialized:
   CUDA Toolkit 12.5, Driver 12.4
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA RTX A6000" (47 GiB, sm_86, mempool enabled)
     "cuda:1"   : "NVIDIA RTX A6000" (47 GiB, sm_86, mempool enabled)
   CUDA peer access:
     Supported fully (all-directional)
   Kernel cache:
     /home/a/.cache/warp/1.3.1
[__init__()] self.cfg: 
 lr: 0.0001
c_in: 6
zfar: 'Infinity'
debug: null
n_view: 1
run_id: 3wy8qqex
use_BN: true
exp_name: 2024-01-11-20-02-45
n_epochs: 62
save_dir: /home/bowenw/debug/2024-01-11-20-02-45/
use_mask: false
loss_type: pairwise_valid
optimizer: adam
batch_size: 64
crop_ratio: 1.1
enable_amp: true
use_normal: false
max_num_key: null
warmup_step: -1
input_resize:
- 160
- 160
max_step_val: 1000
vis_interval: 1000
weight_decay: 0
normalize_xyz: true
resume_run_id: null
clip_grad_norm: 'Infinity'
lr_epoch_decay: 500
render_backend: nvdiffrast
train_num_pair: 5
lr_decay_epochs:
- 50
n_epochs_warmup: 1
make_pair_online: false
gradient_max_norm: 'Infinity'
max_step_per_epoch: 10000
n_rendering_workers: 1
save_epoch_interval: 100
n_dataloader_workers: 100
split_objects_across_gpus: true
ckpt_dir: /data/project/FoundationPoseROS2/FoundationPose/learning/training/../../weights/2024-01-11-20-02-45/model_best.pth

[__init__()] self.h5_file:None
[__init__()] Using pretrained model from /data/project/FoundationPoseROS2/FoundationPose/learning/training/../../weights/2024-01-11-20-02-45/model_best.pth
[__init__()] init done
[__init__()] welcome
[__init__()] self.cfg: 
 lr: 0.0001
c_in: 6
zfar: .inf
debug: null
w_rot: 0.1
n_view: 1
run_id: null
use_BN: true
rot_rep: axis_angle
ckpt_dir: /data/project/FoundationPoseROS2/FoundationPose/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth
exp_name: 2023-10-28-18-33-37
save_dir: /tmp/2023-10-28-18-33-37/
loss_type: l2
optimizer: adam
trans_rep: tracknet
batch_size: 64
crop_ratio: 1.2
use_normal: false
BN_momentum: 0.1
max_num_key: null
warmup_step: -1
input_resize:
- 160
- 160
max_step_val: 1000
normal_uint8: false
vis_interval: 1000
weight_decay: 0
n_max_objects: null
normalize_xyz: true
clip_grad_norm: 'Infinity'
rot_normalizer: 0.3490658503988659
trans_normalizer:
- 0.019999999552965164
- 0.019999999552965164
- 0.05000000074505806
max_step_per_epoch: 25000
val_epoch_interval: 10
n_dataloader_workers: 60
enable_amp: true
use_mask: false

[__init__()] self.h5_file:
[__init__()] Using pretrained model from /data/project/FoundationPoseROS2/FoundationPose/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth
[__init__()] init done
[INFO] [1732530266.469593963] [pose_estimation_node]: Camera intrinsic matrix initialized: [[     608.77           0      323.64]
 [          0      607.41      240.36]
 [          0           0           1]]

0: 1024x1024 1 0, 1 1, 1 2, 1 3, 1 4, 1 5, 1 6, 1 7, 1 8, 1 9, 1 10, 2702.9ms
Speed: 23.2ms preprocess, 2702.9ms inference, 0.6ms postprocess per image at shape (1, 3, 1024, 1024)
[INFO] [1732530276.982712725] [pose_estimation_node]: Object 0 selected.
[reset_object()] self.diameter:0.1299038105676658, vox_size:0.006495190528383291
[reset_object()] self.pts:torch.Size([8, 3])
[reset_object()] reset done
[make_rotation_grid()] cam_in_obs:(42, 4, 4)
[make_rotation_grid()] rot_grid:(252, 4, 4)
num original candidates = 252
num of pose after clustering: 252
[make_rotation_grid()] after cluster, rot_grid:(252, 4, 4)
[make_rotation_grid()] self.rot_grid: torch.Size([252, 4, 4])
[register()] Welcome
Module Utils 64702ec load on device 'cuda:0' took 0.35 ms  (cached)
[register()] valid too small, return
[guess_translation()] valid is empty
[track_one()] Please init pose by register first
Traceback (most recent call last):
  File "/data/project/FoundationPoseROS2/./foundationpose_ros_multi.py", line 395, in <module>
    main()
  File "/data/project/FoundationPoseROS2/./foundationpose_ros_multi.py", line 390, in main
    rclpy.spin(node)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 222, in spin
    executor.spin_once()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 739, in spin_once
    self._spin_once_impl(timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 736, in _spin_once_impl
    raise handler.exception()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 239, in __call__
    self._handler.send(None)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 437, in handler
    await call_coroutine(entity, arg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 362, in _execute_subscription
    await await_or_execute(sub.callback, msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 107, in await_or_execute
    return callback(*args)
  File "/data/project/FoundationPoseROS2/./foundationpose_ros_multi.py", line 165, in depth_callback
    self.process_images()
  File "/data/project/FoundationPoseROS2/./foundationpose_ros_multi.py", line 327, in process_images
    pose = pose_est.track_one(rgb=color, depth=depth, K=self.cam_K, iteration=args.track_refine_iter)
  File "/data/project/FoundationPoseROS2/./FoundationPose/estimater.py", line 253, in track_one
    raise RuntimeError
RuntimeError
段错误 (核心已转储)

**Comment by JINAOLONG** [comment]
> Can you share the screen recording, please? Have you made any changes to the code?

Thank you for your answer. I didn't change the code. Here's my screen recording
[video.webm](https://github.com/user-attachments/assets/a7b04339-7b7c-4605-b957-87a11cc23fd9)

**Comment by JINAOLONG** [comment]
> can you provide your topic list please

Thanks a ton for your helpful reply, I figured out the issue—it's because of the depth map's metric system.

**Comment by ammar-n-abbas** [comment]
Okay perfect thanks for pointing out. Yes, probably you have to multiply the depth value by 1000 with the realsense you re using
