### ISSUE TITLE
The parameter file in the weight folder seems to be corrupted

### ISSUE THREAD

**Issue by zxREX20** [ammar-n-abbas/FoundationPoseROS2#9]
After replacing the file from foundationpose, it can run normally

**Comment by ammar-n-abbas** [comment]
what is the error log? Sometimes if it is not correctly downloaded from the google drive (from the bash file), this may result in such an error.

**Comment by zxREX20** [comment]
Traceback (most recent call last):
  File "/home/xizhang/MyProjects/FoundationPoseROS2/foundationpose_ros_multi.py", line 395, in <module>
    main()
  File "/home/xizhang/MyProjects/FoundationPoseROS2/foundationpose_ros_multi.py", line 389, in main
    node = PoseEstimationNode(new_file_paths)
  File "/home/xizhang/MyProjects/FoundationPoseROS2/foundationpose_ros_multi.py", line 144, in __init__
    self.scorer = ScorePredictor()
  File "/home/xizhang/MyProjects/FoundationPoseROS2/./FoundationPose/learning/training/predict_score.py", line 151, in __init__
    ckpt = torch.load(ckpt_dir)
  File "/home/xizhang/miniconda3/envs/foundationpose_ros/lib/python3.10/site-packages/ultralytics/utils/patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
  File "/home/xizhang/miniconda3/envs/foundationpose_ros/lib/python3.10/site-packages/torch/serialization.py", line 993, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/xizhang/miniconda3/envs/foundationpose_ros/lib/python3.10/site-packages/torch/serialization.py", line 447, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
OSError: [Errno 22] Invalid argument

**Comment by ammar-n-abbas** [comment]
Does it work now? Which file did you replace with from foundation_pose?
